services:
  nodejs:
    image: node:20-alpine
    container_name: nodejs
    ports:
      - 3000:3000
    volumes:
      - ./app:/app
    working_dir: /app
    command: npm start
    env_file:
      - ./app/.env
