services:
  nodejs:
    build:
      context: .
      dockerfile: _docker/nodejs/Dockerfile
      target: production
    container_name: nodejs
    ports:
      - 3000:3000
    volumes:
      - ./app:/app
      - /app/node_modules
    working_dir: /app
    command: npm run dev
    env_file:
      - ./.env
